version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2023-04-20T17-56-55Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: thuanbuidepchai
      MINIO_ROOT_PASSWORD: vodichtoanvutru
    command: server --console-address ':9001' /data
